### ISSUE TITLE
Not able to run

### ISSUE THREAD

**Issue by GirishKumarSharma** [ajithbobby/Stock_Market_Forecasting#1]
As always, Github code never runs without error, and you people never test the code, so same here : 
df = pdr.get_data_tiingo('TTM', api_key=key )

ValueError: The tiingo API key must be provided either through the api_key variable or through the environmental variable TIINGO_API_KEY.

Google fail. No help. Newcomers like me, just read the code and if ever tries to test, as always, only errors....

**Comment by ajithbobby** [comment]
You need to generate an API key from tiingo in order to run this code.

**Comment by GirishKumarSharma** [comment]
And how to generate that API key? Any steps please?

**Comment by ajithbobby** [comment]
1) Go to https://www.tiingo.com/
2) Sign up And Click the API part 
3) In API part, we would see a section called documentation in which we could generate our own API key

**Comment by GirishKumarSharma** [comment]
After obtaining the key (which is called a token in tiingo.com) this is error stack : 

`KeyError                                  Traceback (most recent call last)`
`File ~/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py:3800, in Index.get_loc(self, key, method, tolerance)`
`   3799 try:`
`-> 3800     return self._engine.get_loc(casted_key)`
`   3801 except KeyError as err:`
``
`File ~/.local/lib/python3.10/site-packages/pandas/_libs/index.pyx:138, in pandas._libs.index.IndexEngine.get_loc()`
``
`File ~/.local/lib/python3.10/site-packages/pandas/_libs/index.pyx:165, in pandas._libs.index.IndexEngine.get_loc()`
``
`File pandas/_libs/hashtable_class_helper.pxi:5745, in pandas._libs.hashtable.PyObjectHashTable.get_item()`
``
`File pandas/_libs/hashtable_class_helper.pxi:5753, in pandas._libs.hashtable.PyObjectHashTable.get_item()`
``
`KeyError: 'date'`
``
`The above exception was the direct cause of the following exception:`
``
`KeyError                                  Traceback (most recent call last)`
`Input In [6], in <cell line: 1>()`
`----> 1 df = pdr.get_data_tiingo('TTM', api_key=key )`
``
`File ~/.local/lib/python3.10/site-packages/pandas_datareader/data.py:120, in get_data_tiingo(*args, **kwargs)`
`    119 def get_data_tiingo(*args, **kwargs):`
`--> 120     return TiingoDailyReader(*args, **kwargs).read()`
``
`File ~/.local/lib/python3.10/site-packages/pandas_datareader/tiingo.py:231, in TiingoDailyReader.read(self)`
`    229 self._symbol = symbol`
`    230 try:`
`--> 231     dfs.append(self._read_one_data(self.url, self.params))`
`    232 finally:`
`    233     self.close()`
``
`File ~/.local/lib/python3.10/site-packages/pandas_datareader/tiingo.py:216, in TiingoDailyReader._read_one_data(self, url, params)`
`    211 headers = {`
`    212     "Content-Type": "application/json",`
`    213     "Authorization": "Token " + self.api_key,`
`    214 }`
`    215 out = self._get_response(url, params=params, headers=headers).json()`
`--> 216 return self._read_lines(out)`
``
`File ~/.local/lib/python3.10/site-packages/pandas_datareader/tiingo.py:221, in TiingoDailyReader._read_lines(self, out)`
`    219 df = pd.DataFrame(out)`
`    220 df["symbol"] = self._symbol`
`--> 221 df["date"] = pd.to_datetime(df["date"])`
`    222 df = df.set_index(["symbol", "date"])`
`    223 return df`
``
`File ~/.local/lib/python3.10/site-packages/pandas/core/frame.py:3805, in DataFrame.__getitem__(self, key)`
`   3803 if self.columns.nlevels > 1:`
`   3804     return self._getitem_multilevel(key)`
`-> 3805 indexer = self.columns.get_loc(key)`
`   3806 if is_integer(indexer):`
`   3807     indexer = [indexer]`
``
`File ~/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py:3802, in Index.get_loc(self, key, method, tolerance)`
`   3800     return self._engine.get_loc(casted_key)`
`   3801 except KeyError as err:`
`-> 3802     raise KeyError(key) from err`
`   3803 except TypeError:`
`   3804     # If we have a listlike key, _check_indexing_error will raise`
`   3805     #  InvalidIndexError. Otherwise we fall through and re-raise`
`   3806     #  the TypeError.`
`   3807     self._check_indexing_error(key)`
``
`KeyError: 'date'`

Between, may I know what does it mean by TTM (ticker code, from where did you got)

**Comment by GirishKumarSharma** [comment]
Removed the folder.  Wastage of time.
